FROM golang:1.24-bookworm

# Instalar dependências extras, ferramentas, etc.
RUN apt-get update && apt-get install -y \
    git \
    curl

RUN apt-get update && apt-get install -y librdkafka-dev

# Instalar apenas dockerize (binário)
RUN curl -L https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | tar -C /usr/local/bin -xzv

WORKDIR /workspace

CMD ["sleep", "infinity"]