FROM node:20

# Instalar dependências extras, ferramentas, etc.
RUN apt-get update && apt-get install -y \
    git \
    curl

WORKDIR /workspace

# Instalar apenas dockerize (binário)
RUN curl -L https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | tar -C /usr/local/bin -xzv

CMD ["sleep", "infinity"]
