FROM golang:1.24-bookworm

# Set the Current Working Directory inside the container
# WORKDIR /workspace

# Install system dependencies if needed (uncomment/add as necessary)
# RUN apt-get update && apt-get install -y make curl git

# Copy go.mod and go.sum files as cache layers
# COPY go.mod go.sum ./

# Download dependencies
# RUN go mod download

# Copy the rest of the application code
# COPY . .

# (Optional) Build step - uncomment if you want to build ahead of time
# RUN go build -o app .

RUN apt-get update && apt-get install -y make curl git


# Set default command to bash, you may want to change this
CMD [ "tail", "-f", "/dev/null" ]
